import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import "@/localization/i18n";
import { PaginationProvider } from "@/contexts/PaginationContext";
import { SearchProvider } from "@/contexts/SearchContext";
import { SpinnerProvider } from "@/contexts/SpinnerContext";

const DMSans = DM_Sans({
  weight: ["100", "200", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${DMSans.className} antialiased`}>
        <SpinnerProvider>
          <PaginationProvider>
            <SearchProvider>{children}</SearchProvider>
          </PaginationProvider>
        </SpinnerProvider>
      </body>
    </html>
  );
}
